name: Dockerized PHPUnit Tests

on:
  push:
    branches:
      - master

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Docker
        run: docker-compose up -d

      - name: Install dependencies
        run: docker-compose exec -T app composer install

      - name: Run PHPUnit tests
        run: docker-compose exec -T app ./vendor/bin/phpunit --configuration=phpunit.xml
